# Generated by Django 6.0.6 on 2026-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
